// Фразовые глаголы — 200 записей. Порядок соответствует исходному списку.
// Формат записи: [фразовый глагол, значение (рус.), пример (англ.), пример (рус.)]
// Повторы глаголов с разными значениями — отдельные записи.
window.PHRASAL_VERBS = [
["add up to something","равняться, составлять в сумме","Your purchases add up to $24.","Ваши покупки составляют в сумме 24 доллара."],
["ask around","расспрашивать многих об одном и том же","I asked around but nobody has seen my wallet.","Я расспрашивал всех вокруг, но никто не видел мой кошелёк."],
["ask somebody out","пригласить на свидание","Brian asked Judy out to dinner.","Брайан пригласил Джуди на ужин."],
["back something up","сдавать назад","You'll have to back up your car so that I can get out.","Тебе придётся сдать машину назад, чтобы я мог выйти."],
["back somebody up","поддерживать","My wife backed me up over my decision to quit my job.","Жена поддержала меня в решении уволиться."],
["blow up","взрываться","The racing car blew up after it crashed into the fence.","Гоночный автомобиль взорвался после того, как врезался в ограждение."],
["blow something up","надувать","We have to blow 50 balloons up for the party.","Нам нужно надуть 50 шариков к вечеринке."],
["break down","ломаться (о машине, механизме)","Our car broke down at the side of the highway in the snowstorm.","Наша машина сломалась на обочине шоссе в метель."],
["break down","расстраиваться, срываться","The woman broke down when the police told her that her son had died.","Женщина разрыдалась, когда полиция сообщила ей о смерти сына."],
["break something down","разделять на более мелкие части","Our teacher broke the final project down into three separate parts.","Учитель разбил итоговый проект на три отдельные части."],
["break in","вламываться","Somebody broke in last night and stole our stereo.","Кто-то вломился к нам прошлой ночью и украл музыкальный центр."],
["break into something","проникать силой","The firemen had to break into the room to rescue the children.","Пожарным пришлось взломать дверь в комнату, чтобы спасти детей."],
["break something in","разнашивать, обживать вещь","I need to break these shoes in before we run next week.","Мне нужно разносить эти туфли до забега на следующей неделе."],
["break in","прерывать, вклиниваться","The TV station broke in to report the news of the president's death.","Телеканал прервал передачу, чтобы сообщить о смерти президента."],
["break up","расставаться","My boyfriend and I broke up before I moved to America.","Мы с парнем расстались до того, как я переехала в Америку."],
["break up","рассмеяться (разг.)","The kids just broke up as soon as the clown started talking.","Дети так и покатились со смеху, как только клоун заговорил."],
["break out","сбегать","The prisoners broke out of jail when the guards weren't looking.","Заключённые сбежали из тюрьмы, когда охранники не смотрели."],
["break out in something","покрываться сыпью, высыпаниями","I broke out in a rash after our camping trip.","После похода я покрылась сыпью."],
["bring somebody down","расстраивать, угнетать","This sad music is bringing me down.","Эта грустная музыка наводит на меня тоску."],
["bring somebody up","воспитывать ребёнка","My grandparents brought me up after my parents died.","После смерти родителей меня воспитали бабушка с дедушкой."],
["bring something up","поднимать тему в разговоре","My mother walks out of the room when my father brings up sports.","Мама выходит из комнаты, когда папа заводит разговор о спорте."],
["bring something up","вырвать, стошнить","He drank so much that he brought his dinner up in the toilet.","Он так много выпил, что его стошнило ужином в туалете."],
["call around","обзванивать разные места и людей","We called around but we weren't able to find the car part we needed.","Мы обзвонили кучу мест, но так и не нашли нужную деталь."],
["call somebody back","перезванивать","I called the company back but the offices were closed for the weekend.","Я перезвонил в компанию, но офисы были закрыты на выходные."],
["call something off","отменять","Jason called the wedding off because he wasn't in love with his fiancé.","Джейсон отменил свадьбу, потому что не любил свою невесту."],
["call on somebody","вызывать для ответа","The professor called on me for question 1.","Профессор вызвал меня отвечать на первый вопрос."],
["call on somebody","заходить к кому-либо в гости","We called on you last night but you weren't home.","Мы заходили к вам вчера вечером, но вас не было дома."],
["call somebody up","звонить по телефону","Give me your phone number and I will call you up when we are in town.","Дай мне свой номер, и я позвоню тебе, когда мы будем в городе."],
["calm down","успокаиваться","You are still mad. You need to calm down before you drive the car.","Ты всё ещё злишься. Тебе нужно успокоиться, прежде чем садиться за руль."],
["not care for somebody/ something","не любить (офиц.)","I don't care for his behaviour.","Мне не нравится его поведение."],
["catch up","догонять, достигать того же уровня","You'll have to run faster than that if you want to catch up with Marty.","Тебе придётся бежать быстрее, если хочешь догнать Марти."],
["check in","регистрироваться в отеле или аэропорту","We will get the hotel keys when we check in.","Мы получим ключи от номера, когда зарегистрируемся."],
["check out","выезжать из отеля","You have to check out of the hotel before 11:00 AM.","Нужно выехать из отеля до 11 утра."],
["check somebody/ something out","внимательно проверять, расследовать","The company checks out all new employees.","Компания проверяет всех новых сотрудников."],
["check out somebody/ something","посмотреть, взглянуть (разг.)","Check out the crazy hair on that guy!","Глянь на безумную причёску того парня!"],
["cheer up","становиться веселее","She cheered up when she heard the good news.","Она воспряла духом, когда услышала хорошую новость."],
["cheer somebody up","поднимать настроение","I brought you some flowers to cheer you up.","Я принёс тебе цветы, чтобы поднять настроение."],
["chip in","помогать, скидываться","If everyone chips in we can get the kitchen painted by noon.","Если все помогут, мы покрасим кухню к обеду."],
["clean something up","прибирать, наводить чистоту","Please clean up your bedroom before you go outside.","Пожалуйста, уберись в своей комнате, прежде чем идти гулять."],
["come across something","натыкаться, находить случайно","I came across these old photos when I was tidying the closet.","Я наткнулся на эти старые фотографии, когда разбирал шкаф."],
["come apart","распадаться на части","The top and bottom come apart if you pull hard enough.","Верхняя и нижняя части разделяются, если потянуть достаточно сильно."],
["come down with something","заболеть чем-либо","My nephew came down with chicken pox this weekend.","Мой племянник заболел ветрянкой на этих выходных."],
["come forward","вызваться, предоставить информацию","The woman came forward with her husband's finger prints.","Женщина пришла и предоставила отпечатки пальцев своего мужа."],
["come from some place","происходить откуда-либо","The art of origami comes from Asia.","Искусство оригами происходит из Азии."],
["count on somebody/ something","рассчитывать на кого-либо/что-либо","I am counting on you to make dinner while I am out.","Я рассчитываю, что ты приготовишь ужин, пока меня не будет."],
["cross something out","вычёркивать","Please cross out your old address and write your new one.","Пожалуйста, вычеркни старый адрес и напиши новый."],
["cut back on something","сокращать потребление чего-либо","My doctor wants me to cut back on sweets and fatty foods.","Врач хочет, чтобы я ел меньше сладкого и жирного."],
["cut something down","срубать, валить","We had to cut the old tree in our yard down after the storm.","После шторма нам пришлось спилить старое дерево во дворе."],
["cut in","вмешиваться, перебивать","Your father cut in while I was dancing with your uncle.","Твой отец вмешался, когда я танцевала с твоим дядей."],
["cut in","подрезать на дороге","The bus driver got angry when that car cut in.","Водитель автобуса рассердился, когда та машина подрезала его."],
["cut in","включаться автоматически","The air conditioner cuts in when the temperature gets to 22°C.","Кондиционер включается, когда температура достигает 22°C."],
["cut something off","отрезать, ампутировать","The doctors cut off his leg because it was severely injured.","Врачи ампутировали ему ногу, потому что она была сильно повреждена."],
["cut something off","прекращать подачу, отключать","The phone company cut off our phone because we didn't pay the bill.","Телефонная компания отключила нам телефон, потому что мы не оплатили счёт."],
["cut somebody off","лишать наследства","My grandparents cut my father off when he remarried.","Бабушка с дедушкой лишили моего отца наследства, когда он женился повторно."],
["cut something out","вырезать","I cut this ad out of the newspaper.","Я вырезал это объявление из газеты."],
["do somebody/ something over","избивать, громить (брит., разг.)","He's lucky to be alive. His shop was done over by a street gang.","Ему повезло остаться в живых. Его магазин разгромила уличная банда."],
["do something over","переделывать заново (амер.)","My teacher wants me to do my essay over because she doesn't like my topic.","Учительница хочет, чтобы я переписал эссе, потому что ей не нравится моя тема."],
["do away with something","избавляться от чего-либо","It's time to do away with all of these old tax records.","Пора избавиться от всех этих старых налоговых документов."],
["do something up","застёгивать, закрывать","Do your coat up before you go outside. It's snowing!","Застегни пальто, прежде чем выходить. Идёт снег!"],
["dress up","наряжаться","It's a fancy restaurant so we have to dress up.","Это фешенебельный ресторан, поэтому нам нужно нарядиться."],
["drop back","откатываться назад (в позиции, группе)","Andrea dropped back to third place when she fell off her bike.","Андреа откатилась на третье место, когда упала с велосипеда."],
["drop in/ by/ over","заходить без приглашения","I might drop in/by/over for tea sometime this week.","Я могу заглянуть на чай на этой неделе."],
["drop somebody/ something off","подвозить, высаживать","I have to drop my sister off at work before I come over.","Мне нужно сначала завезти сестру на работу, прежде чем приехать к тебе."],
["drop out","бросать учёбу","I dropped out of Science because it was too difficult.","Я бросил естественные науки, потому что это было слишком сложно."],
["eat out","есть в ресторане","I don't feel like cooking tonight. Let's eat out.","Мне не хочется готовить сегодня вечером. Давай поедим где-нибудь."],
["end up","оказаться в итоге","We ended up renting a movie instead of going to the theatre.","В итоге мы взяли фильм напрокат вместо того, чтобы идти в театр."],
["fall apart","распадаться на части","My new dress fell apart in the washing machine.","Моё новое платье развалилось в стиральной машине."],
["fall down","падать на землю","The picture that you hung up last night fell down this morning.","Картина, которую ты повесил вчера вечером, упала этим утром."],
["fall out","выпадать откуда-либо","The money must have fallen out of my pocket.","Деньги, должно быть, выпали из моего кармана."],
["fall out","выпадать (о волосах, зубах)","His hair started to fall out when he was only 35.","У него начали выпадать волосы, когда ему было всего 35."],
["figure something out","понять, разобраться","I need to figure out how to fit the piano and the bookshelf in this room.","Мне нужно придумать, как разместить пианино и книжный шкаф в этой комнате."],
["fill something in","заполнять (брит.)","Please fill in the form with your name, address, and phone number.","Пожалуйста, заполните форму: имя, адрес и номер телефона."],
["fill something out","заполнять (амер.)","The form must be filled out in capital letters.","Форму нужно заполнять печатными буквами."],
["fill something up","наполнять доверху","I always fill the water jug up when it is empty.","Я всегда наполняю кувшин водой, когда он пустой."],
["find out","узнавать, выяснять","We don't know where he lives. How can we find out?","Мы не знаем, где он живёт. Как мы можем это выяснить?"],
["find something out","узнать, разузнать","We tried to keep the time of the party a secret, but Samantha found it out.","Мы пытались сохранить время вечеринки в секрете, но Саманта узнала."],
["get something across/ over","донести мысль, объяснить","I tried to get my point across/over to the judge but she wouldn't listen.","Я пытался донести свою мысль до судьи, но она не слушала."],
["get along/on","ладить друг с другом","I was surprised how well my new girlfriend and my sister got along/on.","Я был удивлён, как хорошо ладят моя новая девушка и моя сестра."],
["get around","передвигаться","My grandfather can get around fine in his new wheelchair.","Мой дедушка отлично передвигается на своей новой инвалидной коляске."],
["get away","выбраться в отпуск","We worked so hard this year that we had to get away for a week.","Мы так много работали в этом году, что нам нужно было выбраться на неделю отдохнуть."],
["get away with something","сделать что-либо безнаказанно","Jason always gets away with cheating in his maths tests.","Джейсон всегда выходит сухим из воды, когда списывает на контрольных по математике."],
["get back","возвращаться","We got back from our vacation last week.","Мы вернулись с отпуска на прошлой неделе."],
["get something back","получить обратно","Liz finally got her Science notes back from my roommate.","Лиз наконец получила свои конспекты обратно от моего соседа по комнате."],
["get back at somebody","отомстить кому-либо","My sister got back at me for stealing her shoes. She stole my favourite hat.","Сестра отомстила мне за то, что я взял её туфли. Она украла мою любимую шляпу."],
["get back into something","снова увлечься чем-либо","I finally got back into my novel and finished it.","Я наконец снова увлёкся своим романом и закончил его."],
["get on something","сесть в транспорт","We're going to freeze out here if you don't let us get on the bus.","Мы замёрзнем здесь, если ты не впустишь нас в автобус."],
["get over something","оправиться от чего-либо","I just got over the flu and now my sister has it.","Я только что оправился от гриппа, а теперь им заболела моя сестра."],
["get over something","преодолеть проблему","The company will have to close if it can't get over the new regulations.","Компании придётся закрыться, если она не сможет справиться с новыми правилами."],
["get round to something","наконец найти время для чего-либо","I don't know when I am going to get round to writing the thank you cards.","Не знаю, когда я соберусь написать благодарственные открытки."],
["get together","собираться вместе","Let's get together for a BBQ this weekend.","Давай соберёмся на барбекю в эти выходные."],
["get up","вставать с постели","I got up early today to study for my exam.","Сегодня я встал пораньше, чтобы подготовиться к экзамену."],
["get up","вставать на ноги","You should get up and give the elderly man your seat.","Тебе стоит встать и уступить место пожилому мужчине."],
["give somebody away","выдать кого-либо","His wife gave him away to the police.","Его жена выдала его полиции."],
["give somebody away","вести невесту к алтарю","My father gave me away at my wedding.","Отец вёл меня к алтарю на моей свадьбе."],
["give something away","испортить секрет","My little sister gave the surprise party away by accident.","Моя младшая сестра случайно проболталась о вечеринке-сюрпризе."],
["give something away","отдавать бесплатно","The library was giving away old books on Friday.","В пятницу библиотека раздавала старые книги бесплатно."],
["give something back","возвращать взятое","I have to give these skates back to Franz before his hockey game.","Я должен вернуть эти коньки Францу до его хоккейного матча."],
["give in","неохотно уступать","My boyfriend didn't want to go to the ballet, but he finally gave in.","Мой парень не хотел идти на балет, но в конце концов уступил."],
["give something out","раздавать (обычно бесплатно)","They were giving out free perfume samples at the department store.","В универмаге раздавали бесплатные пробники парфюма."],
["give something up","бросать привычку","I am giving up smoking as of January 1st.","Я бросаю курить с первого января."],
["give up","прекращать попытки","My maths homework was too difficult so I gave up.","Домашка по математике была слишком сложной, поэтому я сдался."],
["go after somebody","преследовать кого-либо","My brother tried to go after the thief in his car.","Мой брат попытался преследовать вора на своей машине."],
["go after something","добиваться чего-либо","I went after my dream and now I am a published writer.","Я последовал за своей мечтой, и теперь я публикующийся писатель."],
["go against somebody","соревноваться, противостоять","We are going against the best soccer team in the city tonight.","Сегодня вечером мы играем против лучшей футбольной команды города."],
["go ahead","начинать, продолжать","Please go ahead and eat before the food gets cold.","Ешь, пока еда не остыла."],
["go back","возвращаться куда-либо","I have to go back home and get my lunch.","Мне нужно вернуться домой и забрать свой обед."],
["go out","выходить куда-либо развлечься","We're going out for dinner tonight.","Сегодня вечером мы идём ужинать куда-нибудь."],
["go out with somebody","встречаться с кем-либо","Jesse has been going out with Luke since they met last winter.","Джесси встречается с Люком с тех пор, как они познакомились прошлой зимой."],
["go over something","просматривать, повторять","Please go over your answers before you submit your test.","Проверь свои ответы, прежде чем сдавать тест."],
["go over","зайти в гости неподалёку","I haven't seen Tina for a long time. I think I'll go over for an hour or two.","Я давно не видела Тину. Думаю, зайду к ней на часик-другой."],
["go without something","обходиться без чего-либо","When I was young, we went without winter boots.","Когда я был маленьким, мы обходились без зимних ботинок."],
["grow apart","отдаляться друг от друга","My best friend and I grew apart after she changed schools.","Мы с лучшей подругой отдалились друг от друга после того, как она сменила школу."],
["grow back","отрастать заново","My roses grew back this summer.","Мои розы отросли этим летом."],
["grow into something","дорасти до чего-либо","This bike is too big for him now, but he should grow into it by next year.","Этот велосипед пока слишком велик для него, но к следующему году он должен до него дорасти."],
["grow out of something","вырасти из чего-либо","Elizabeth needs a new pair of shoes because she has grown out of her old ones.","Элизабет нужна новая пара обуви, потому что она выросла из старой."],
["grow up","взрослеть","When Jack grows up he wants to be a fireman.","Когда Джек вырастет, он хочет стать пожарным."],
["hand something down","передавать вещи другим","I handed my old comic books down to my little cousin.","Я отдал свои старые комиксы младшему двоюродному брату."],
["hand something in","сдавать работу","I have to hand in my essay by Friday.","Мне нужно сдать эссе до пятницы."],
["hand something out","раздавать группе людей","We will hand out the invitations at the door.","Мы раздадим приглашения у входа."],
["hand something over","отдавать (обычно неохотно)","The police asked the man to hand over his wallet and his weapons.","Полиция попросила мужчину отдать бумажник и оружие."],
["hang in","держаться, не сдаваться (разг.)","Hang in there. I'm sure you'll find a job very soon.","Держись. Уверен, ты очень скоро найдёшь работу."],
["hang on","подождать немного (разг.)","Hang on while I grab my coat and shoes!","Подожди, пока я возьму пальто и туфли!"],
["hang out","проводить время неформально (разг.)","Instead of going to the party we are just going to hang out at my place.","Вместо вечеринки мы просто посидим у меня дома."],
["hang up","вешать трубку","He didn't say goodbye before he hung up.","Он не попрощался, прежде чем повесить трубку."],
["hold somebody/ something back","удерживать, сдерживать","I had to hold my dog back because there was a cat in the park.","Мне пришлось удерживать мою собаку, потому что в парке была кошка."],
["hold something back","скрывать эмоцию","Jamie held back his tears at his grandfather's funeral.","Джейми сдерживал слёзы на похоронах своего дедушки."],
["hold on","подождать","Please hold on while I transfer you to the Sales Department.","Пожалуйста, подождите, пока я переведу вас на отдел продаж."],
["hold onto somebody/ something","крепко держаться","Hold onto your hat because it's very windy outside.","Держись за шляпу, на улице очень ветрено."],
["hold somebody/ something up","грабить","A man in a black mask held the bank up this morning.","Сегодня утром человек в чёрной маске ограбил банк."],
["keep on doing something","продолжать что-то делать","Keep on stirring until the liquid comes to a boil.","Продолжай помешивать, пока жидкость не закипит."],
["keep something from somebody","скрывать что-то от кого-то","We kept our relationship from our parents for two years.","Мы скрывали наши отношения от родителей два года."],
["keep somebody/ something out","не допускать внутрь","Try to keep the wet dog out of the living room.","Постарайся не пускать мокрую собаку в гостиную."],
["keep something up","продолжать в том же темпе","If you keep those results up you will get into a great college.","Если ты сохранишь такие результаты, то поступишь в отличный колледж."],
["let somebody down","подводить","I need you to be on time. Don't let me down this time.","Мне нужно, чтобы ты пришёл вовремя. Не подведи меня в этот раз."],
["let somebody in","впускать","Can you let the cat in before you go to school?","Можешь впустить кошку, прежде чем пойдёшь в школу?"],
["log in (or on)","входить в систему","I can't log in to Facebook because I've forgotten my password.","Я не могу войти в Facebook, потому что забыл пароль."],
["log out (or off)","выходить из системы","If you don't log off somebody could get into your account.","Если ты не выйдешь из системы, кто-нибудь сможет попасть в твой аккаунт."],
["look after somebody/ something","заботиться о ком-то или чём-то","I have to look after my sick grandmother.","Мне нужно ухаживать за больной бабушкой."],
["look down on somebody","смотреть на кого-то свысока","Ever since we stole that chocolate bar your dad has looked down on me.","С тех пор как мы украли тот шоколадный батончик, твой папа смотрит на меня свысока."],
["look for somebody/ something","искать","I'm looking for a red dress for the wedding.","Я ищу красное платье на свадьбу."],
["look forward to something","с нетерпением ждать чего-то","I'm looking forward to the Christmas break.","Я с нетерпением жду рождественских каникул."],
["look into something","изучать, расследовать","We are going to look into the price of snowboards today.","Сегодня мы изучим цены на сноуборды."],
["look out","быть осторожным","Look out! That car's going to hit you!","Осторожно! Та машина сейчас тебя собьёт!"],
["look out for somebody/ something","высматривать","Don't forget to look out for snakes on the hiking trail.","Не забывай высматривать змей на туристической тропе."],
["look something over","осматривать, проверять","Can you look over my essay for spelling mistakes?","Можешь проверить моё эссе на орфографические ошибки?"],
["look something up","искать информацию в справочнике или базе","We can look her phone number up on the Internet.","Мы можем найти её номер телефона в интернете."],
["look up to somebody","уважать, восхищаться кем-то","My little sister has always looked up to me.","Моя младшая сестра всегда восхищалась мной."],
["make something up","выдумывать, лгать","Josie made up a story about why we were late.","Джози выдумала историю о том, почему мы опоздали."],
["make up","мириться","We were angry last night, but we made up at breakfast.","Вчера вечером мы злились друг на друга, но за завтраком помирились."],
["make somebody up","красить кого-то, гримировать","My sisters made me up for my graduation party.","Сёстры накрасили меня к вечеринке по случаю выпускного."],
["mix something up","путать что-то","I mixed up the twins' names again!","Я снова перепутал имена близнецов!"],
["pass away","умирать","His uncle passed away last night after a long illness.","Его дядя скончался вчера ночью после долгой болезни."],
["pass out","терять сознание","It was so hot in the church that an elderly lady passed out.","В церкви было так жарко, что пожилая женщина потеряла сознание."],
["pass something out","раздавать одно и то же многим","The professor passed the textbooks out before class.","Профессор раздал учебники перед занятием."],
["pass something up","отказываться (обычно от чего-то хорошего)","I passed up the job because I am afraid of change.","Я отказался от работы, потому что боюсь перемен."],
["pay somebody back","возвращать долг","Thanks for buying my ticket. I'll pay you back on Friday.","Спасибо, что купил мне билет. Я верну тебе деньги в пятницу."],
["pay for something","поплатиться за что-то плохое","That bully will pay for being mean to my little brother.","Тот задира поплатится за то, что обижал моего младшего брата."],
["pick something out","выбирать","I picked out three sweaters for you to try on.","Я выбрал три свитера, чтобы ты их примерил."],
["point somebody/ something out","указывать пальцем","I'll point my boyfriend out when he runs by.","Я укажу на своего парня, когда он будет пробегать мимо."],
["put something down","положить на поверхность или пол","You can put the groceries down on the kitchen counter.","Можешь положить продукты на кухонную стойку."],
["put somebody down","оскорблять, принижать","The students put the substitute teacher down because his pants were too short.","Ученики унижали замещающего учителя, потому что у него были слишком короткие брюки."],
["put something off","откладывать","We are putting off our trip until January because of the hurricane.","Мы откладываем поездку до января из-за урагана."],
["put something out","тушить","The neighbours put the fire out before the firemen arrived.","Соседи потушили пожар до приезда пожарных."],
["put something together","собирать, монтировать","I have to put the crib together before the baby arrives.","Мне нужно собрать детскую кроватку до рождения малыша."],
["put up with somebody/ something","терпеть","I don't think I can put up with three small children in the car.","Не думаю, что смогу вытерпеть троих маленьких детей в машине."],
["put something on","надевать","Don't forget to put on your new earrings for the party.","Не забудь надеть новые серьги на вечеринку."],
["run into somebody/ something","случайно встретить","I ran into an old school-friend at the mall.","Я случайно встретил старого школьного друга в торговом центре."],
["run over somebody/ something","переехать","I accidentally ran over your bicycle in the driveway.","Я случайно переехал твой велосипед на подъездной дорожке."],
["run over/ through something","отрепетировать, повторить","Let's run over/through these lines one more time before the show.","Давай повторим эти реплики ещё раз перед выступлением."],
["run away","уйти неожиданно, сбежать","The child ran away from home and has been missing for three days.","Ребёнок сбежал из дома и отсутствует уже три дня."],
["run out","заканчиваться, иссякать","We ran out of shampoo so I had to wash my hair with soap.","У нас закончился шампунь, поэтому мне пришлось мыть голову мылом."],
["send something back","вернуть обратно (обычно по почте)","My letter got sent back to me because I used the wrong stamp.","Моё письмо вернулось ко мне, потому что я наклеил неправильную марку."],
["set something up","организовывать, устраивать","Our boss set a meeting up with the president of the company.","Наш босс организовал встречу с президентом компании."],
["set somebody up","обмануть, подставить","The police set up the car thief by using a hidden camera.","Полиция подставила угонщика машин, использовав скрытую камеру."],
["shop around","сравнивать цены","I want to shop around a little before I decide on these boots.","Я хочу немного сравнить цены, прежде чем решиться на эти ботинки."],
["show off","красоваться, хвастаться","He always shows off on his skateboard","Он всегда красуется на своём скейтборде"],
["sleep over","оставаться ночевать (разг.)","You should sleep over tonight if the weather is too bad to drive home.","Тебе стоит переночевать здесь сегодня, если погода слишком плохая, чтобы ехать домой."],
["sort something out","организовать, разрешить проблему","We need to sort the bills out before the first of the month.","Нам нужно разобраться со счетами до первого числа месяца."],
["stick to something","придерживаться чего-либо","You will lose weight if you stick to the diet.","Ты похудеешь, если будешь придерживаться диеты."],
["switch something off","выключать","The light's too bright. Could you switch it off.","Свет слишком яркий. Не мог бы ты его выключить."],
["switch something on","включать","We heard the news as soon as we switched on the car radio.","Мы услышали новости, как только включили автомобильное радио."],
["take after somebody","быть похожим на члена семьи","I take after my mother. We are both impatient.","Я похожа на маму. Мы обе нетерпеливые."],
["take something apart","разбирать на части","He took the car brakes apart and found the problem.","Он разобрал тормоза машины и нашёл неисправность."],
["take something back","возвращать покупку","I have to take our new TV back because it doesn't work.","Мне придётся вернуть наш новый телевизор, потому что он не работает."],
["take off","взлетать","My plane takes off in five minutes.","Мой самолёт взлетает через пять минут."],
["take something off","снимать (обычно одежду)","Take off your socks and shoes and come in the lake!","Снимай носки и ботинки и заходи в озеро!"],
["take something out","выносить, убирать","Can you take the garbage out to the street for me?","Можешь вынести за меня мусор на улицу?"],
["take somebody out","приглашать куда-либо за свой счёт","My grandparents took us out for dinner and a movie.","Бабушка с дедушкой пригласили нас на ужин и в кино."],
["tear something up","рвать на куски","I tore up my ex-boyfriend's letters and gave them back to him.","Я порвала письма бывшего парня и отдала их ему обратно."],
["think back","вспоминать","When I think back on my youth, I wish I had studied harder.","Когда я вспоминаю свою юность, мне жаль, что я не учился усерднее."],
["think something over","обдумывать","I'll have to think this job offer over before I make my final decision.","Мне нужно обдумать это предложение о работе, прежде чем принять окончательное решение."],
["throw something away","выбрасывать","We threw our old furniture away when we won the lottery.","Мы выбросили старую мебель, когда выиграли в лотерею."],
["turn something down","убавлять громкость или силу","Please turn the TV down while the guests are here.","Пожалуйста, убавь телевизор, пока гости здесь."],
["turn something down","отказываться","I turned the job down because I don't want to move.","Я отказался от работы, потому что не хочу переезжать."],
["turn something off","выключать","Your mother wants you to turn the TV off and come for dinner.","Мама хочет, чтобы ты выключил телевизор и пришёл ужинать."],
["turn something on","включать","It's too dark in here. Let's turn some lights on.","Здесь слишком темно. Давай включим свет."],
["turn something up","прибавлять громкость или силу","Can you turn the music up? This is my favourite song.","Можешь прибавить музыку? Это моя любимая песня."],
["turn up","объявляться неожиданно","Our cat turned up after we put posters up all over the neighbourhood.","Наш кот объявился после того, как мы развесили объявления по всему району."],
["try something on","примерять одежду","I'm going to try these jeans on, but I don't think they will fit.","Я собираюсь примерить эти джинсы, но не думаю, что они подойдут."],
["try something out","испытывать, тестировать","I am going to try this new brand of detergent out.","Я собираюсь испытать этот новый стиральный порошок."],
["use something up","израсходовать полностью","The kids used all of the toothpaste up so we need to buy some more.","Дети израсходовали всю зубную пасту, нужно купить ещё."],
["wake up","просыпаться","We have to wake up early for work on Monday.","Нам приходится вставать рано на работу в понедельник."],
["warm somebody/ something up","согревать","You can warm your feet up in front of the fireplace.","Ты можешь согреть ноги у камина."],
["warm up","разминаться","I always warm up by doing sit-ups before I go for a run.","Перед пробежкой я всегда разминаюсь, качая пресс."],
["wear off","сходить на нет, исчезать","Most of my make-up wore off before I got to the party.","Большая часть моей косметики стёрлась до того, как я добралась до вечеринки."],
["work out","тренироваться","I work out at the gym three times a week.","Я тренируюсь в спортзале три раза в неделю."],
["work out","получаться, удаваться","Our plan worked out fine.","Наш план сработал отлично."],
["work something out","рассчитывать, вычислять","We have to work out the total cost before we buy the house.","Нам нужно рассчитать общую стоимость, прежде чем покупать дом."]
];
